#!/usr/bin/env python3
"""Generate canonical SIGINT Terrain SVG pattern primitives from tokens.json.

Single source of truth: sigint_terrain_bundle/tokens.json.
Output directory: sigint_terrain_bundle/patterns/.

Run from repo root:
    python3 scripts/build_patterns.py
"""

import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOKENS_PATH = REPO_ROOT / "sigint_terrain_bundle" / "tokens.json"
# Canonical location, also served by GitHub Pages (source = /docs).
OUT_DIR = REPO_ROOT / "docs" / "patterns"

SVG_W = 200
SVG_H = 100

PREAMBLE = (
    "<!-- Generated by scripts/build_patterns.py from sigint_terrain_bundle/tokens.json. "
    "Do not edit by hand. -->\n"
)


def svg_open(width=SVG_W, height=SVG_H):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">\n'
    )


def svg_close():
    return "</svg>\n"


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PREAMBLE + content)
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


def stipple_svg(dot_radius_px: float, spacing_px: int, fill: str, label: str) -> str:
    body = svg_open()
    body += f'<rect width="{SVG_W}" height="{SVG_H}" fill="#f4f1ea"/>\n'
    body += f'<g fill="{fill}">\n'
    y = spacing_px / 2
    while y < SVG_H:
        offset = (spacing_px / 2) if int(y / spacing_px) % 2 else 0
        x = offset + spacing_px / 2
        while x < SVG_W:
            body += f'  <circle cx="{x:.2f}" cy="{y:.2f}" r="{dot_radius_px}"/>\n'
            x += spacing_px
        y += spacing_px
    body += "</g>\n"
    body += f'<text x="6" y="{SVG_H - 6}" font-family="monospace" font-size="9" fill="#222">{label}</text>\n'
    body += svg_close()
    return body


def hachure_svg(spacing_px: int, stroke_width_px: float, stroke: str, label: str) -> str:
    body = svg_open()
    body += f'<rect width="{SVG_W}" height="{SVG_H}" fill="#eef0ec"/>\n'
    if spacing_px > 0:
        body += f'<g stroke="{stroke}" stroke-width="{stroke_width_px}" stroke-linecap="round">\n'
        x = -SVG_H
        while x < SVG_W:
            body += f'  <line x1="{x}" y1="{SVG_H}" x2="{x + SVG_H}" y2="0"/>\n'
            x += spacing_px
        body += "</g>\n"
    body += f'<text x="6" y="{SVG_H - 6}" font-family="monospace" font-size="9" fill="#222">{label}</text>\n'
    body += svg_close()
    return body


def crosshatch_svg(stroke: str, fill_tint: str, fill_alpha: float, spacing_px: int, stroke_width: float) -> str:
    body = svg_open()
    body += f'<rect width="{SVG_W}" height="{SVG_H}" fill="#eef0ec"/>\n'
    body += f'<rect width="{SVG_W}" height="{SVG_H}" fill="{fill_tint}" fill-opacity="{fill_alpha}"/>\n'
    body += f'<g stroke="{stroke}" stroke-width="{stroke_width}">\n'
    x = -SVG_H
    while x < SVG_W:
        body += f'  <line x1="{x}" y1="{SVG_H}" x2="{x + SVG_H}" y2="0"/>\n'
        x += spacing_px
    x = -SVG_H
    while x < SVG_W:
        body += f'  <line x1="{x}" y1="0" x2="{x + SVG_H}" y2="{SVG_H}"/>\n'
        x += spacing_px
    body += "</g>\n"
    body += '<text x="6" y="94" font-family="monospace" font-size="9" fill="#fff">DENIED</text>\n'
    body += svg_close()
    return body


def wash_svg(fill: str, alpha: float, label: str) -> str:
    body = svg_open()
    # checkerboard substrate for transparency reference
    body += '<g fill="#dcdcdc">\n'
    for yi in range(0, SVG_H, 10):
        for xi in range(0, SVG_W, 10):
            if (xi // 10 + yi // 10) % 2 == 0:
                body += f'  <rect x="{xi}" y="{yi}" width="10" height="10" fill="#ececec"/>\n'
    body += "</g>\n"
    if alpha > 0:
        body += f'<rect width="{SVG_W}" height="{SVG_H}" fill="{fill}" fill-opacity="{alpha}"/>\n'
    body += f'<text x="6" y="{SVG_H - 6}" font-family="monospace" font-size="9" fill="#111">{label}</text>\n'
    body += svg_close()
    return body


def scan_lines_svg(stroke: str, stroke_width: float, spacing_px: int, alpha: float) -> str:
    body = svg_open()
    body += '<rect width="200" height="100" fill="#0d1014"/>\n'
    body += f'<g stroke="{stroke}" stroke-width="{stroke_width}" stroke-opacity="{alpha * 25:.2f}">\n'
    y = 0
    while y < SVG_H:
        body += f'  <line x1="0" y1="{y}" x2="{SVG_W}" y2="{y}"/>\n'
        y += spacing_px
    body += "</g>\n"
    body += '<text x="6" y="94" font-family="monospace" font-size="9" fill="#9bd1ff" fill-opacity="0.8">SCAN-LIVE</text>\n'
    body += svg_close()
    return body


def hypso_swatch_svg(bands) -> str:
    body = svg_open(width=SVG_W, height=SVG_H)
    band_w = SVG_W / len(bands)
    for i, b in enumerate(bands):
        x = i * band_w
        body += f'  <rect x="{x}" y="0" width="{band_w}" height="{SVG_H - 18}" fill="{b["fill"]}"/>\n'
        body += (
            f'  <text x="{x + 4}" y="{SVG_H - 4}" font-family="monospace" font-size="8" fill="#111">{b["label"]}</text>\n'
        )
    body += svg_close()
    return body


def layer_stack_svg() -> str:
    """Schematic of the 7 canonical layers, side-on."""
    W, H = 520, 240
    body = svg_open(width=W, height=H)
    body += f'<rect width="{W}" height="{H}" fill="#fdfcf8"/>\n'
    layers = [
        ("1. base imagery",                       "#cfd2c7"),
        ("2. hillshade (overlay, 55-65%)",        "#9aa097"),
        ("3. contour / hachure (multiply)",       "#3f4a4f"),
        ("4. confidence stipple (screen)",        "#1c1c1c"),
        ("5. uncertainty wash (by age tier)",     "#e76f51"),
        ("6. denied crosshatch (red family)",     "#b1241c"),
        ("7. scan lines (live feeds, 4%)",        "#9bd1ff"),
    ]
    y = 30
    for name, color in layers:
        body += f'  <rect x="20" y="{y}" width="180" height="14" fill="{color}" fill-opacity="0.85" stroke="#222" stroke-width="0.5"/>\n'
        body += f'  <text x="210" y="{y + 11}" font-family="monospace" font-size="11" fill="#111">{name}</text>\n'
        y += 24
    body += '<text x="20" y="20" font-family="monospace" font-size="11" fill="#111" font-weight="bold">Canonical Layer Order (bottom \u2192 top)</text>\n'
    body += svg_close()
    return body


def main():
    tokens = json.loads(TOKENS_PATH.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Generating SVG patterns into {OUT_DIR.relative_to(REPO_ROOT)}/")

    # Confidence stipple per provenance class
    cs = tokens["palettes"]["confidence_stipple"]
    for c in cs["classes"]:
        write(
            OUT_DIR / f"confidence_stipple_{c['name']}.svg",
            stipple_svg(c["dot_radius_px"], c["spacing_px"], cs["fill"], c["label"]),
        )

    # Slope hachure per slope band (skip the "none" band)
    for s in tokens["palettes"]["slope_severity"]["bands"]:
        if s.get("render") == "none" or s["spacing_px"] == 0:
            continue
        write(
            OUT_DIR / f"slope_hachure_{s['name']}.svg",
            hachure_svg(s["spacing_px"], s["stroke_width_px"], s["stroke"], s["label"]),
        )

    # Denied zone crosshatch
    d = tokens["palettes"]["denied_red_family"]
    write(
        OUT_DIR / "denied_zone_crosshatch.svg",
        crosshatch_svg(d["stroke"], d["fill_tint"], d["fill_tint_alpha"], d["spacing_px"], d["stroke_width_px"]),
    )

    # Uncertainty wash per tier
    for t in tokens["palettes"]["uncertainty_wash_orange_red_family"]["tiers"]:
        write(
            OUT_DIR / f"uncertainty_wash_{t['name'].lower()}.svg",
            wash_svg(t["fill"], t["alpha"], f"{t['name']} ({t['label']})"),
        )

    # Scan line overlay
    sl = tokens["palettes"]["scan_line_overlay"]
    write(
        OUT_DIR / "scan_line_overlay.svg",
        scan_lines_svg(sl["stroke"], sl["stroke_width_px"], sl["spacing_px"], sl["alpha"]),
    )

    # Tactical hypso swatch
    write(
        OUT_DIR / "tactical_hypso_first_5.svg",
        hypso_swatch_svg(tokens["palettes"]["tactical_hypso"]["bands"]),
    )

    # Canonical layer stack schematic
    write(OUT_DIR / "layer_stack.svg", layer_stack_svg())

    print("Done.")


if __name__ == "__main__":
    main()
